# ==== Criacao da tabela ==== #
CREATE TABLE T_CTRL_LIVR_BIBL(
	COD_CTRL  INT NOT NULL AUTO_INCREMENT,
    DATA_ENTR datetime NOT NULL default NOW(),
    DATA_SAID datetime NULL,
    COD_MOTI INT NOT NULL,
    COD_LIVR INT NOT NULL,           	
    PRIMARY KEY (COD_CTRL)
) DEFAULT CHARSET = utf8;

# ==== Criacao da chave estrangeira ==== #
ALTER TABLE T_CTRL_LIVR_BIBL ADD CONSTRAINT fk_mot FOREIGN KEY (COD_MOTI) REFERENCES T_MOTI_BIBL(COD_MOTI);
ALTER TABLE T_CTRL_LIVR_BIBL ADD CONSTRAINT fk_livr FOREIGN KEY (COD_LIVR) REFERENCES T_LIVR_BIBL(COD_LIVR);