# ==== Criacao da tabela ==== #
CREATE TABLE T_LIVR_BIBL(
	COD_LIVR    INT NOT NULL AUTO_INCREMENT,
    NOME_LIVR  VARCHAR(100) NOT NULL,   
    DESC_LIVR  LONGTEXT NULL,
    ANO_EDIC   YEAR NULL,
    NMR_EDIC   INT NULL,
    NOME_AUTOR VARCHAR(100),
    PRIMARY KEY (COD_LIVR)
) DEFAULT CHARSET = utf8;

